# Generated by Django 6.0.2 on 2026-02-21 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="flight",
            old_name="crew",
            new_name="crews",
        ),
    ]
