# Generated by Django 6.0.2 on 2026-02-22 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_rename_crew_flight_crews"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("source", "destination")},
        ),
    ]
